feat: Remove githash from paradedb.version_info() (#4956)
# Ticket(s) Closed

## What

Remove `githash` from `paradedb.version_info()`.

If you load the new shared library before updating the extension,
calling version_info breaks:
```
select paradedb.version_info();
ERROR:  compressed pglz data is corrupt
```
I'm guessing this won't be an issue with the way upgrades are handled
for CNPG deployments, but users could encounter it for manual updates. I
haven't tried it but I believe we could expose two versions of
`version_info` at once, one that returns two values and one that returns
three (the three valued one would return `unknown` for the hash). Maybe
there's a better way to make this more backwards compatible though. Or
maybe it's fine to leave as is. Thoughts?
 
## Why

Right now the build process requires `COMMIT_SHA` to be set to thread it
through to `githash`. This causes problems for Docker Official Images
which doesn't support passing in arguments. Since the version number is
already included, having the hash also is not stricly necessary and
would only be useful in very uncommon scenarios.

## How

## Tests